# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_player.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_player.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\005protoB\014PlayerProtos'),
  serialized_pb=_b('\n\x11game_player.proto\"`\n\nGamePlayer\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04xPos\x18\x03 \x01(\x05\x12\x0c\n\x04yPos\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x05\x12\r\n\x05image\x18\x06 \x02(\x05\x42\x15\n\x05protoB\x0cPlayerProtos')
)




_GAMEPLAYER = _descriptor.Descriptor(
  name='GamePlayer',
  full_name='GamePlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GamePlayer.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='GamePlayer.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xPos', full_name='GamePlayer.xPos', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yPos', full_name='GamePlayer.yPos', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='GamePlayer.score', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='GamePlayer.image', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['GamePlayer'] = _GAMEPLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GamePlayer = _reflection.GeneratedProtocolMessageType('GamePlayer', (_message.Message,), dict(
  DESCRIPTOR = _GAMEPLAYER,
  __module__ = 'game_player_pb2'
  # @@protoc_insertion_point(class_scope:GamePlayer)
  ))
_sym_db.RegisterMessage(GamePlayer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
